server:
  port: 8130 # 服务端口

spring:
  profiles:
    active: dev # 环境设置
  application:
    name: service-oss # 服务名

  cloud:
    nacos:
      discovery:
        server-addr: 43.139.42.95:8848 # nacos服务地址

aliyun:
  oss:
    endpoint: oss-cn-hangzhou.aliyuncs.com
    key-id: LTAI5tHS4xt9SHqxXc9RNvw2
    key-secret: 8DeWvI0poSpRcqNVFRwfOejFz3E2jC
    bucketName: srb-file1-2022-08
